#!/bin/sh

git push origin -d v2.9.2
git tag -d v2.9.2
git pull origin SFOS
git tag v2.9.2
## works only foar annotated tags: git push origin main --follow-tags
git push origin SFOS
git push origin --tags
