#!/bin/sh

version=2.9.2
release=25
tag=v"$version"rel"$release"
git push origin -d $tag
git tag -d $tag
git pull origin sfos-dev
git tag $tag
## works only foar annotated tags: git push origin main --follow-tags
git push origin sfos-dev
# git push origin --tags
git push origin $tag
